"""adiciona_tabela_outbox

Revision ID: 9354169c5639
Revises: a40024fc524d
Create Date: 2026-05-14 11:53:12.771471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9354169c5639'
down_revision: Union[str, None] = 'a40024fc524d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_mensagens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo_evento', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('processado', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_processamento', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outbox_mensagens')
    # ### end Alembic commands ###
